[workspace]
resolver = "2"
members = [
    'node',
    'runtime',
]

[patch."https://github.com/paritytech/substrate"]
sc-consensus-manual-seal = { path = "client/consensus/manual-seal" }

[profile.release]
panic = 'unwind'
